// This file is auto-generated by @tanstack/router-plugin on `pnpm dev`.
// Do not edit manually. Re-run dev or build to regenerate.

import { createFileRoute, createRootRouteWithContext } from '@tanstack/react-router'
import type { QueryClient } from '@tanstack/react-query'

import { Route as RootRoute } from './routes/__root.js'
import { Route as IndexRoute } from './routes/index.js'
import { Route as SignInRoute } from './routes/sign-in.js'
import { Route as AuthenticatedRoute } from './routes/_authenticated.js'
import { Route as DashboardRoute } from './routes/_authenticated/dashboard.js'
import { Route as ApplicationsRoute } from './routes/_authenticated/applications.js'

const routeTree = RootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  AuthenticatedRoute.addChildren([DashboardRoute, ApplicationsRoute]),
])

export { routeTree }
