/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRoundsRouteImport } from './routes/api/rounds'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedShortlistRouteImport } from './routes/_authenticated/shortlist'
import { Route as AuthenticatedRoundsRouteImport } from './routes/_authenticated/rounds'
import { Route as AuthenticatedRecordRouteImport } from './routes/_authenticated/record'
import { Route as AuthenticatedProgrammesRouteImport } from './routes/_authenticated/programmes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedRoundsIndexRouteImport } from './routes/_authenticated/rounds.index'
import { Route as AuthenticatedProgrammesIndexRouteImport } from './routes/_authenticated/programmes.index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as ApiRoundRoundIdRouteImport } from './routes/api/round.$roundId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAdminMappingsRouteImport } from './routes/api/admin.mappings'
import { Route as ApiAdminIngestsRouteImport } from './routes/api/admin.ingests'
import { Route as ApiAdminClientsRouteImport } from './routes/api/admin.clients'
import { Route as ApiAdminCanonicalFieldsRouteImport } from './routes/api/admin.canonical-fields'
import { Route as AuthenticatedRoundsRoundIdRouteImport } from './routes/_authenticated/rounds.$roundId'
import { Route as AuthenticatedProgrammesProgrammeIdRouteImport } from './routes/_authenticated/programmes.$programmeId'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'
import { Route as ApiAdminMappingsIdRouteImport } from './routes/api/admin.mappings.$id'
import { Route as ApiAdminIngestsIdRouteImport } from './routes/api/admin.ingests.$id'
import { Route as ApiAdminIngestsIdResolveRouteImport } from './routes/api/admin.ingests.$id.resolve'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoundsRoute = ApiRoundsRouteImport.update({
  id: '/api/rounds',
  path: '/api/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShortlistRoute = AuthenticatedShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoundsRoute = AuthenticatedRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordRoute = AuthenticatedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgrammesRoute = AuthenticatedProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoundsIndexRoute =
  AuthenticatedRoundsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoundsRoute,
  } as any)
const AuthenticatedProgrammesIndexRoute =
  AuthenticatedProgrammesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProgrammesRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiRoundRoundIdRoute = ApiRoundRoundIdRouteImport.update({
  id: '/api/round/$roundId',
  path: '/api/round/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMappingsRoute = ApiAdminMappingsRouteImport.update({
  id: '/api/admin/mappings',
  path: '/api/admin/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestsRoute = ApiAdminIngestsRouteImport.update({
  id: '/api/admin/ingests',
  path: '/api/admin/ingests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClientsRoute = ApiAdminClientsRouteImport.update({
  id: '/api/admin/clients',
  path: '/api/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCanonicalFieldsRoute = ApiAdminCanonicalFieldsRouteImport.update({
  id: '/api/admin/canonical-fields',
  path: '/api/admin/canonical-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoundsRoundIdRoute =
  AuthenticatedRoundsRoundIdRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => AuthenticatedRoundsRoute,
  } as any)
const AuthenticatedProgrammesProgrammeIdRoute =
  AuthenticatedProgrammesProgrammeIdRouteImport.update({
    id: '/$programmeId',
    path: '/$programmeId',
    getParentRoute: () => AuthenticatedProgrammesRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiAdminMappingsIdRoute = ApiAdminMappingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminMappingsRoute,
} as any)
const ApiAdminIngestsIdRoute = ApiAdminIngestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminIngestsRoute,
} as any)
const ApiAdminIngestsIdResolveRoute =
  ApiAdminIngestsIdResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiAdminIngestsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/no-access': typeof NoAccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programmes': typeof AuthenticatedProgrammesRouteWithChildren
  '/record': typeof AuthenticatedRecordRoute
  '/rounds': typeof AuthenticatedRoundsRouteWithChildren
  '/shortlist': typeof AuthenticatedShortlistRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/programmes/$programmeId': typeof AuthenticatedProgrammesProgrammeIdRoute
  '/rounds/$roundId': typeof AuthenticatedRoundsRoundIdRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/programmes/': typeof AuthenticatedProgrammesIndexRoute
  '/rounds/': typeof AuthenticatedRoundsIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/no-access': typeof NoAccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/record': typeof AuthenticatedRecordRoute
  '/shortlist': typeof AuthenticatedShortlistRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/programmes/$programmeId': typeof AuthenticatedProgrammesProgrammeIdRoute
  '/rounds/$roundId': typeof AuthenticatedRoundsRoundIdRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/programmes': typeof AuthenticatedProgrammesIndexRoute
  '/rounds': typeof AuthenticatedRoundsIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programmes': typeof AuthenticatedProgrammesRouteWithChildren
  '/_authenticated/record': typeof AuthenticatedRecordRoute
  '/_authenticated/rounds': typeof AuthenticatedRoundsRouteWithChildren
  '/_authenticated/shortlist': typeof AuthenticatedShortlistRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/programmes/$programmeId': typeof AuthenticatedProgrammesProgrammeIdRoute
  '/_authenticated/rounds/$roundId': typeof AuthenticatedRoundsRoundIdRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/programmes/': typeof AuthenticatedProgrammesIndexRoute
  '/_authenticated/rounds/': typeof AuthenticatedRoundsIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/no-access'
    | '/sign-in'
    | '/sign-up'
    | '/applications'
    | '/dashboard'
    | '/profile'
    | '/programmes'
    | '/record'
    | '/rounds'
    | '/shortlist'
    | '/users'
    | '/api/apply'
    | '/api/rounds'
    | '/applications/$applicationId'
    | '/programmes/$programmeId'
    | '/rounds/$roundId'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/auth/$'
    | '/api/round/$roundId'
    | '/applications/'
    | '/programmes/'
    | '/rounds/'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/ingests/$id/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/no-access'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/profile'
    | '/record'
    | '/shortlist'
    | '/users'
    | '/api/apply'
    | '/api/rounds'
    | '/applications/$applicationId'
    | '/programmes/$programmeId'
    | '/rounds/$roundId'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/auth/$'
    | '/api/round/$roundId'
    | '/applications'
    | '/programmes'
    | '/rounds'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/ingests/$id/resolve'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/no-access'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/programmes'
    | '/_authenticated/record'
    | '/_authenticated/rounds'
    | '/_authenticated/shortlist'
    | '/_authenticated/users'
    | '/api/apply'
    | '/api/rounds'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/programmes/$programmeId'
    | '/_authenticated/rounds/$roundId'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/auth/$'
    | '/api/round/$roundId'
    | '/_authenticated/applications/'
    | '/_authenticated/programmes/'
    | '/_authenticated/rounds/'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/ingests/$id/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiRoundsRoute: typeof ApiRoundsRoute
  ApiAdminCanonicalFieldsRoute: typeof ApiAdminCanonicalFieldsRoute
  ApiAdminClientsRoute: typeof ApiAdminClientsRoute
  ApiAdminIngestsRoute: typeof ApiAdminIngestsRouteWithChildren
  ApiAdminMappingsRoute: typeof ApiAdminMappingsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRoundRoundIdRoute: typeof ApiRoundRoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rounds': {
      id: '/api/rounds'
      path: '/api/rounds'
      fullPath: '/api/rounds'
      preLoaderRoute: typeof ApiRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shortlist': {
      id: '/_authenticated/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof AuthenticatedShortlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rounds': {
      id: '/_authenticated/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof AuthenticatedRoundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/record': {
      id: '/_authenticated/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthenticatedRecordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programmes': {
      id: '/_authenticated/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AuthenticatedProgrammesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rounds/': {
      id: '/_authenticated/rounds/'
      path: '/'
      fullPath: '/rounds/'
      preLoaderRoute: typeof AuthenticatedRoundsIndexRouteImport
      parentRoute: typeof AuthenticatedRoundsRoute
    }
    '/_authenticated/programmes/': {
      id: '/_authenticated/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof AuthenticatedProgrammesIndexRouteImport
      parentRoute: typeof AuthenticatedProgrammesRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/round/$roundId': {
      id: '/api/round/$roundId'
      path: '/api/round/$roundId'
      fullPath: '/api/round/$roundId'
      preLoaderRoute: typeof ApiRoundRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mappings': {
      id: '/api/admin/mappings'
      path: '/api/admin/mappings'
      fullPath: '/api/admin/mappings'
      preLoaderRoute: typeof ApiAdminMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingests': {
      id: '/api/admin/ingests'
      path: '/api/admin/ingests'
      fullPath: '/api/admin/ingests'
      preLoaderRoute: typeof ApiAdminIngestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clients': {
      id: '/api/admin/clients'
      path: '/api/admin/clients'
      fullPath: '/api/admin/clients'
      preLoaderRoute: typeof ApiAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/canonical-fields': {
      id: '/api/admin/canonical-fields'
      path: '/api/admin/canonical-fields'
      fullPath: '/api/admin/canonical-fields'
      preLoaderRoute: typeof ApiAdminCanonicalFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rounds/$roundId': {
      id: '/_authenticated/rounds/$roundId'
      path: '/$roundId'
      fullPath: '/rounds/$roundId'
      preLoaderRoute: typeof AuthenticatedRoundsRoundIdRouteImport
      parentRoute: typeof AuthenticatedRoundsRoute
    }
    '/_authenticated/programmes/$programmeId': {
      id: '/_authenticated/programmes/$programmeId'
      path: '/$programmeId'
      fullPath: '/programmes/$programmeId'
      preLoaderRoute: typeof AuthenticatedProgrammesProgrammeIdRouteImport
      parentRoute: typeof AuthenticatedProgrammesRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/admin/mappings/$id': {
      id: '/api/admin/mappings/$id'
      path: '/$id'
      fullPath: '/api/admin/mappings/$id'
      preLoaderRoute: typeof ApiAdminMappingsIdRouteImport
      parentRoute: typeof ApiAdminMappingsRoute
    }
    '/api/admin/ingests/$id': {
      id: '/api/admin/ingests/$id'
      path: '/$id'
      fullPath: '/api/admin/ingests/$id'
      preLoaderRoute: typeof ApiAdminIngestsIdRouteImport
      parentRoute: typeof ApiAdminIngestsRoute
    }
    '/api/admin/ingests/$id/resolve': {
      id: '/api/admin/ingests/$id/resolve'
      path: '/resolve'
      fullPath: '/api/admin/ingests/$id/resolve'
      preLoaderRoute: typeof ApiAdminIngestsIdResolveRouteImport
      parentRoute: typeof ApiAdminIngestsIdRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedProgrammesRouteChildren {
  AuthenticatedProgrammesProgrammeIdRoute: typeof AuthenticatedProgrammesProgrammeIdRoute
  AuthenticatedProgrammesIndexRoute: typeof AuthenticatedProgrammesIndexRoute
}

const AuthenticatedProgrammesRouteChildren: AuthenticatedProgrammesRouteChildren =
  {
    AuthenticatedProgrammesProgrammeIdRoute:
      AuthenticatedProgrammesProgrammeIdRoute,
    AuthenticatedProgrammesIndexRoute: AuthenticatedProgrammesIndexRoute,
  }

const AuthenticatedProgrammesRouteWithChildren =
  AuthenticatedProgrammesRoute._addFileChildren(
    AuthenticatedProgrammesRouteChildren,
  )

interface AuthenticatedRoundsRouteChildren {
  AuthenticatedRoundsRoundIdRoute: typeof AuthenticatedRoundsRoundIdRoute
  AuthenticatedRoundsIndexRoute: typeof AuthenticatedRoundsIndexRoute
}

const AuthenticatedRoundsRouteChildren: AuthenticatedRoundsRouteChildren = {
  AuthenticatedRoundsRoundIdRoute: AuthenticatedRoundsRoundIdRoute,
  AuthenticatedRoundsIndexRoute: AuthenticatedRoundsIndexRoute,
}

const AuthenticatedRoundsRouteWithChildren =
  AuthenticatedRoundsRoute._addFileChildren(AuthenticatedRoundsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgrammesRoute: typeof AuthenticatedProgrammesRouteWithChildren
  AuthenticatedRecordRoute: typeof AuthenticatedRecordRoute
  AuthenticatedRoundsRoute: typeof AuthenticatedRoundsRouteWithChildren
  AuthenticatedShortlistRoute: typeof AuthenticatedShortlistRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgrammesRoute: AuthenticatedProgrammesRouteWithChildren,
  AuthenticatedRecordRoute: AuthenticatedRecordRoute,
  AuthenticatedRoundsRoute: AuthenticatedRoundsRouteWithChildren,
  AuthenticatedShortlistRoute: AuthenticatedShortlistRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAdminIngestsIdRouteChildren {
  ApiAdminIngestsIdResolveRoute: typeof ApiAdminIngestsIdResolveRoute
}

const ApiAdminIngestsIdRouteChildren: ApiAdminIngestsIdRouteChildren = {
  ApiAdminIngestsIdResolveRoute: ApiAdminIngestsIdResolveRoute,
}

const ApiAdminIngestsIdRouteWithChildren =
  ApiAdminIngestsIdRoute._addFileChildren(ApiAdminIngestsIdRouteChildren)

interface ApiAdminIngestsRouteChildren {
  ApiAdminIngestsIdRoute: typeof ApiAdminIngestsIdRouteWithChildren
}

const ApiAdminIngestsRouteChildren: ApiAdminIngestsRouteChildren = {
  ApiAdminIngestsIdRoute: ApiAdminIngestsIdRouteWithChildren,
}

const ApiAdminIngestsRouteWithChildren = ApiAdminIngestsRoute._addFileChildren(
  ApiAdminIngestsRouteChildren,
)

interface ApiAdminMappingsRouteChildren {
  ApiAdminMappingsIdRoute: typeof ApiAdminMappingsIdRoute
}

const ApiAdminMappingsRouteChildren: ApiAdminMappingsRouteChildren = {
  ApiAdminMappingsIdRoute: ApiAdminMappingsIdRoute,
}

const ApiAdminMappingsRouteWithChildren =
  ApiAdminMappingsRoute._addFileChildren(ApiAdminMappingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiRoundsRoute: ApiRoundsRoute,
  ApiAdminCanonicalFieldsRoute: ApiAdminCanonicalFieldsRoute,
  ApiAdminClientsRoute: ApiAdminClientsRoute,
  ApiAdminIngestsRoute: ApiAdminIngestsRouteWithChildren,
  ApiAdminMappingsRoute: ApiAdminMappingsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRoundRoundIdRoute: ApiRoundRoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
