/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAwardsRouteImport } from './routes/_authenticated/awards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedPartnershipsRouteImport } from './routes/_authenticated/partnerships'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgrammesRouteImport } from './routes/_authenticated/programmes'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoundsRouteImport } from './routes/_authenticated/rounds'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShortlistRouteImport } from './routes/_authenticated/shortlist'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiDigestUnsubscribeRouteImport } from './routes/api/digest-unsubscribe'
import { Route as ApiRoundsRouteImport } from './routes/api/rounds'
import { Route as ApiSubmitReportRouteImport } from './routes/api/submit-report'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'
import { Route as AuthenticatedAwardsIndexRouteImport } from './routes/_authenticated/awards.index'
import { Route as AuthenticatedAwardsAwardIdRouteImport } from './routes/_authenticated/awards.$awardId'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedFinanceBalanceRouteImport } from './routes/_authenticated/finance.balance'
import { Route as AuthenticatedPartnershipsIndexRouteImport } from './routes/_authenticated/partnerships.index'
import { Route as AuthenticatedPartnershipsPartnershipIdRouteImport } from './routes/_authenticated/partnerships.$partnershipId'
import { Route as AuthenticatedProgrammesIndexRouteImport } from './routes/_authenticated/programmes.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsReportKeyRouteImport } from './routes/_authenticated/reports.$reportKey'
import { Route as AuthenticatedRoundsIndexRouteImport } from './routes/_authenticated/rounds.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings.activity'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings.api-keys'
import { Route as AuthenticatedSettingsAwardLetterRouteImport } from './routes/_authenticated/settings.award-letter'
import { Route as AuthenticatedSettingsBudgetRouteImport } from './routes/_authenticated/settings.budget'
import { Route as AuthenticatedSettingsDataImportRouteImport } from './routes/_authenticated/settings.data-import'
import { Route as AuthenticatedSettingsGivingStrategyRouteImport } from './routes/_authenticated/settings.giving-strategy'
import { Route as AuthenticatedSettingsSubmissionsRouteImport } from './routes/_authenticated/settings.submissions'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsVotingRouteImport } from './routes/_authenticated/settings.voting'
import { Route as AuthenticatedShortlistIndexRouteImport } from './routes/_authenticated/shortlist.index'
import { Route as AuthenticatedShortlistSetUpAwardsRouteImport } from './routes/_authenticated/shortlist.set-up-awards'
import { Route as ApiAdminAwardsRouteImport } from './routes/api/admin.awards'
import { Route as ApiAdminCanonicalFieldsRouteImport } from './routes/api/admin.canonical-fields'
import { Route as ApiAdminClientsRouteImport } from './routes/api/admin.clients'
import { Route as ApiAdminDeprivationProbeRouteImport } from './routes/api/admin.deprivation-probe'
import { Route as ApiAdminIngestsRouteImport } from './routes/api/admin.ingests'
import { Route as ApiAdminMappingsRouteImport } from './routes/api/admin.mappings'
import { Route as ApiAdminReportCanonicalFieldsRouteImport } from './routes/api/admin.report-canonical-fields'
import { Route as ApiAdminReportIngestsRouteImport } from './routes/api/admin.report-ingests'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAvatarUserIdRouteImport } from './routes/api/avatar.$userId'
import { Route as ApiCronFinanceDigestRouteImport } from './routes/api/cron.finance-digest'
import { Route as ApiInternalPipelineRouteImport } from './routes/api/internal.pipeline'
import { Route as ApiRoundRoundIdRouteImport } from './routes/api/round.$roundId'
import { Route as ApiAdminIngestsIdRouteImport } from './routes/api/admin.ingests.$id'
import { Route as ApiAdminMappingsIdRouteImport } from './routes/api/admin.mappings.$id'
import { Route as ApiAdminReportIngestsIdRouteImport } from './routes/api/admin.report-ingests.$id'
import { Route as ApiWebhooksTypeformTokenRouteImport } from './routes/api/webhooks.typeform.$token'
import { Route as ApiAdminIngestsIdReprocessRouteImport } from './routes/api/admin.ingests.$id.reprocess'
import { Route as ApiAdminIngestsIdResolveRouteImport } from './routes/api/admin.ingests.$id.resolve'
import { Route as ApiAdminReportIngestsIdResolveRouteImport } from './routes/api/admin.report-ingests.$id.resolve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAwardsRoute = AuthenticatedAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnershipsRoute =
  AuthenticatedPartnershipsRouteImport.update({
    id: '/partnerships',
    path: '/partnerships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgrammesRoute = AuthenticatedProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoundsRoute = AuthenticatedRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShortlistRoute = AuthenticatedShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestUnsubscribeRoute = ApiDigestUnsubscribeRouteImport.update({
  id: '/api/digest-unsubscribe',
  path: '/api/digest-unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoundsRoute = ApiRoundsRouteImport.update({
  id: '/api/rounds',
  path: '/api/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitReportRoute = ApiSubmitReportRouteImport.update({
  id: '/api/submit-report',
  path: '/api/submit-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedAwardsIndexRoute =
  AuthenticatedAwardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAwardsRoute,
  } as any)
const AuthenticatedAwardsAwardIdRoute =
  AuthenticatedAwardsAwardIdRouteImport.update({
    id: '/$awardId',
    path: '/$awardId',
    getParentRoute: () => AuthenticatedAwardsRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBalanceRoute =
  AuthenticatedFinanceBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedPartnershipsIndexRoute =
  AuthenticatedPartnershipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnershipsRoute,
  } as any)
const AuthenticatedPartnershipsPartnershipIdRoute =
  AuthenticatedPartnershipsPartnershipIdRouteImport.update({
    id: '/$partnershipId',
    path: '/$partnershipId',
    getParentRoute: () => AuthenticatedPartnershipsRoute,
  } as any)
const AuthenticatedProgrammesIndexRoute =
  AuthenticatedProgrammesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProgrammesRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsReportKeyRoute =
  AuthenticatedReportsReportKeyRouteImport.update({
    id: '/$reportKey',
    path: '/$reportKey',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedRoundsIndexRoute =
  AuthenticatedRoundsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoundsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAwardLetterRoute =
  AuthenticatedSettingsAwardLetterRouteImport.update({
    id: '/award-letter',
    path: '/award-letter',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBudgetRoute =
  AuthenticatedSettingsBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDataImportRoute =
  AuthenticatedSettingsDataImportRouteImport.update({
    id: '/data-import',
    path: '/data-import',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGivingStrategyRoute =
  AuthenticatedSettingsGivingStrategyRouteImport.update({
    id: '/giving-strategy',
    path: '/giving-strategy',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSubmissionsRoute =
  AuthenticatedSettingsSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsVotingRoute =
  AuthenticatedSettingsVotingRouteImport.update({
    id: '/voting',
    path: '/voting',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedShortlistIndexRoute =
  AuthenticatedShortlistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShortlistRoute,
  } as any)
const AuthenticatedShortlistSetUpAwardsRoute =
  AuthenticatedShortlistSetUpAwardsRouteImport.update({
    id: '/set-up-awards',
    path: '/set-up-awards',
    getParentRoute: () => AuthenticatedShortlistRoute,
  } as any)
const ApiAdminAwardsRoute = ApiAdminAwardsRouteImport.update({
  id: '/api/admin/awards',
  path: '/api/admin/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCanonicalFieldsRoute = ApiAdminCanonicalFieldsRouteImport.update({
  id: '/api/admin/canonical-fields',
  path: '/api/admin/canonical-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClientsRoute = ApiAdminClientsRouteImport.update({
  id: '/api/admin/clients',
  path: '/api/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeprivationProbeRoute =
  ApiAdminDeprivationProbeRouteImport.update({
    id: '/api/admin/deprivation-probe',
    path: '/api/admin/deprivation-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminIngestsRoute = ApiAdminIngestsRouteImport.update({
  id: '/api/admin/ingests',
  path: '/api/admin/ingests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMappingsRoute = ApiAdminMappingsRouteImport.update({
  id: '/api/admin/mappings',
  path: '/api/admin/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportCanonicalFieldsRoute =
  ApiAdminReportCanonicalFieldsRouteImport.update({
    id: '/api/admin/report-canonical-fields',
    path: '/api/admin/report-canonical-fields',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminReportIngestsRoute = ApiAdminReportIngestsRouteImport.update({
  id: '/api/admin/report-ingests',
  path: '/api/admin/report-ingests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarUserIdRoute = ApiAvatarUserIdRouteImport.update({
  id: '/api/avatar/$userId',
  path: '/api/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFinanceDigestRoute = ApiCronFinanceDigestRouteImport.update({
  id: '/api/cron/finance-digest',
  path: '/api/cron/finance-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalPipelineRoute = ApiInternalPipelineRouteImport.update({
  id: '/api/internal/pipeline',
  path: '/api/internal/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoundRoundIdRoute = ApiRoundRoundIdRouteImport.update({
  id: '/api/round/$roundId',
  path: '/api/round/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestsIdRoute = ApiAdminIngestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminIngestsRoute,
} as any)
const ApiAdminMappingsIdRoute = ApiAdminMappingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminMappingsRoute,
} as any)
const ApiAdminReportIngestsIdRoute = ApiAdminReportIngestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminReportIngestsRoute,
} as any)
const ApiWebhooksTypeformTokenRoute =
  ApiWebhooksTypeformTokenRouteImport.update({
    id: '/api/webhooks/typeform/$token',
    path: '/api/webhooks/typeform/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminIngestsIdReprocessRoute =
  ApiAdminIngestsIdReprocessRouteImport.update({
    id: '/reprocess',
    path: '/reprocess',
    getParentRoute: () => ApiAdminIngestsIdRoute,
  } as any)
const ApiAdminIngestsIdResolveRoute =
  ApiAdminIngestsIdResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiAdminIngestsIdRoute,
  } as any)
const ApiAdminReportIngestsIdResolveRoute =
  ApiAdminReportIngestsIdResolveRouteImport.update({
    id: '/resolve',
    path: '/resolve',
    getParentRoute: () => ApiAdminReportIngestsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/no-access': typeof NoAccessRoute
  '/platform': typeof PlatformRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/awards': typeof AuthenticatedAwardsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/partnerships': typeof AuthenticatedPartnershipsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/programmes': typeof AuthenticatedProgrammesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/rounds': typeof AuthenticatedRoundsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/shortlist': typeof AuthenticatedShortlistRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/digest-unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/awards/$awardId': typeof AuthenticatedAwardsAwardIdRoute
  '/finance/balance': typeof AuthenticatedFinanceBalanceRoute
  '/partnerships/$partnershipId': typeof AuthenticatedPartnershipsPartnershipIdRoute
  '/reports/$reportKey': typeof AuthenticatedReportsReportKeyRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/award-letter': typeof AuthenticatedSettingsAwardLetterRoute
  '/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/settings/data-import': typeof AuthenticatedSettingsDataImportRoute
  '/settings/giving-strategy': typeof AuthenticatedSettingsGivingStrategyRoute
  '/settings/submissions': typeof AuthenticatedSettingsSubmissionsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/voting': typeof AuthenticatedSettingsVotingRoute
  '/shortlist/set-up-awards': typeof AuthenticatedShortlistSetUpAwardsRoute
  '/api/admin/awards': typeof ApiAdminAwardsRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/deprivation-probe': typeof ApiAdminDeprivationProbeRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/admin/report-canonical-fields': typeof ApiAdminReportCanonicalFieldsRoute
  '/api/admin/report-ingests': typeof ApiAdminReportIngestsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/cron/finance-digest': typeof ApiCronFinanceDigestRoute
  '/api/internal/pipeline': typeof ApiInternalPipelineRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/awards/': typeof AuthenticatedAwardsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/partnerships/': typeof AuthenticatedPartnershipsIndexRoute
  '/programmes/': typeof AuthenticatedProgrammesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/rounds/': typeof AuthenticatedRoundsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shortlist/': typeof AuthenticatedShortlistIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/report-ingests/$id': typeof ApiAdminReportIngestsIdRouteWithChildren
  '/api/webhooks/typeform/$token': typeof ApiWebhooksTypeformTokenRoute
  '/api/admin/ingests/$id/reprocess': typeof ApiAdminIngestsIdReprocessRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
  '/api/admin/report-ingests/$id/resolve': typeof ApiAdminReportIngestsIdResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/no-access': typeof NoAccessRoute
  '/platform': typeof PlatformRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/digest-unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/awards/$awardId': typeof AuthenticatedAwardsAwardIdRoute
  '/finance/balance': typeof AuthenticatedFinanceBalanceRoute
  '/partnerships/$partnershipId': typeof AuthenticatedPartnershipsPartnershipIdRoute
  '/reports/$reportKey': typeof AuthenticatedReportsReportKeyRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/award-letter': typeof AuthenticatedSettingsAwardLetterRoute
  '/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/settings/data-import': typeof AuthenticatedSettingsDataImportRoute
  '/settings/giving-strategy': typeof AuthenticatedSettingsGivingStrategyRoute
  '/settings/submissions': typeof AuthenticatedSettingsSubmissionsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/voting': typeof AuthenticatedSettingsVotingRoute
  '/shortlist/set-up-awards': typeof AuthenticatedShortlistSetUpAwardsRoute
  '/api/admin/awards': typeof ApiAdminAwardsRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/deprivation-probe': typeof ApiAdminDeprivationProbeRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/admin/report-canonical-fields': typeof ApiAdminReportCanonicalFieldsRoute
  '/api/admin/report-ingests': typeof ApiAdminReportIngestsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/cron/finance-digest': typeof ApiCronFinanceDigestRoute
  '/api/internal/pipeline': typeof ApiInternalPipelineRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/awards': typeof AuthenticatedAwardsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/partnerships': typeof AuthenticatedPartnershipsIndexRoute
  '/programmes': typeof AuthenticatedProgrammesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/rounds': typeof AuthenticatedRoundsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shortlist': typeof AuthenticatedShortlistIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/report-ingests/$id': typeof ApiAdminReportIngestsIdRouteWithChildren
  '/api/webhooks/typeform/$token': typeof ApiWebhooksTypeformTokenRoute
  '/api/admin/ingests/$id/reprocess': typeof ApiAdminIngestsIdReprocessRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
  '/api/admin/report-ingests/$id/resolve': typeof ApiAdminReportIngestsIdResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/no-access': typeof NoAccessRoute
  '/platform': typeof PlatformRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/awards': typeof AuthenticatedAwardsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/partnerships': typeof AuthenticatedPartnershipsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programmes': typeof AuthenticatedProgrammesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/rounds': typeof AuthenticatedRoundsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/shortlist': typeof AuthenticatedShortlistRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/digest-unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/rounds': typeof ApiRoundsRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/awards/$awardId': typeof AuthenticatedAwardsAwardIdRoute
  '/_authenticated/finance/balance': typeof AuthenticatedFinanceBalanceRoute
  '/_authenticated/partnerships/$partnershipId': typeof AuthenticatedPartnershipsPartnershipIdRoute
  '/_authenticated/reports/$reportKey': typeof AuthenticatedReportsReportKeyRoute
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/award-letter': typeof AuthenticatedSettingsAwardLetterRoute
  '/_authenticated/settings/budget': typeof AuthenticatedSettingsBudgetRoute
  '/_authenticated/settings/data-import': typeof AuthenticatedSettingsDataImportRoute
  '/_authenticated/settings/giving-strategy': typeof AuthenticatedSettingsGivingStrategyRoute
  '/_authenticated/settings/submissions': typeof AuthenticatedSettingsSubmissionsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/voting': typeof AuthenticatedSettingsVotingRoute
  '/_authenticated/shortlist/set-up-awards': typeof AuthenticatedShortlistSetUpAwardsRoute
  '/api/admin/awards': typeof ApiAdminAwardsRoute
  '/api/admin/canonical-fields': typeof ApiAdminCanonicalFieldsRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/deprivation-probe': typeof ApiAdminDeprivationProbeRoute
  '/api/admin/ingests': typeof ApiAdminIngestsRouteWithChildren
  '/api/admin/mappings': typeof ApiAdminMappingsRouteWithChildren
  '/api/admin/report-canonical-fields': typeof ApiAdminReportCanonicalFieldsRoute
  '/api/admin/report-ingests': typeof ApiAdminReportIngestsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/cron/finance-digest': typeof ApiCronFinanceDigestRoute
  '/api/internal/pipeline': typeof ApiInternalPipelineRoute
  '/api/round/$roundId': typeof ApiRoundRoundIdRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/awards/': typeof AuthenticatedAwardsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/partnerships/': typeof AuthenticatedPartnershipsIndexRoute
  '/_authenticated/programmes/': typeof AuthenticatedProgrammesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/rounds/': typeof AuthenticatedRoundsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shortlist/': typeof AuthenticatedShortlistIndexRoute
  '/api/admin/ingests/$id': typeof ApiAdminIngestsIdRouteWithChildren
  '/api/admin/mappings/$id': typeof ApiAdminMappingsIdRoute
  '/api/admin/report-ingests/$id': typeof ApiAdminReportIngestsIdRouteWithChildren
  '/api/webhooks/typeform/$token': typeof ApiWebhooksTypeformTokenRoute
  '/api/admin/ingests/$id/reprocess': typeof ApiAdminIngestsIdReprocessRoute
  '/api/admin/ingests/$id/resolve': typeof ApiAdminIngestsIdResolveRoute
  '/api/admin/report-ingests/$id/resolve': typeof ApiAdminReportIngestsIdResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/no-access'
    | '/platform'
    | '/sign-in'
    | '/sign-up'
    | '/applications'
    | '/awards'
    | '/dashboard'
    | '/finance'
    | '/insights'
    | '/partnerships'
    | '/profile'
    | '/programmes'
    | '/reports'
    | '/rounds'
    | '/settings'
    | '/shortlist'
    | '/users'
    | '/api/apply'
    | '/api/digest-unsubscribe'
    | '/api/rounds'
    | '/api/submit-report'
    | '/applications/$applicationId'
    | '/awards/$awardId'
    | '/finance/balance'
    | '/partnerships/$partnershipId'
    | '/reports/$reportKey'
    | '/settings/activity'
    | '/settings/api-keys'
    | '/settings/award-letter'
    | '/settings/budget'
    | '/settings/data-import'
    | '/settings/giving-strategy'
    | '/settings/submissions'
    | '/settings/team'
    | '/settings/voting'
    | '/shortlist/set-up-awards'
    | '/api/admin/awards'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/deprivation-probe'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/admin/report-canonical-fields'
    | '/api/admin/report-ingests'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/cron/finance-digest'
    | '/api/internal/pipeline'
    | '/api/round/$roundId'
    | '/applications/'
    | '/awards/'
    | '/finance/'
    | '/partnerships/'
    | '/programmes/'
    | '/reports/'
    | '/rounds/'
    | '/settings/'
    | '/shortlist/'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/report-ingests/$id'
    | '/api/webhooks/typeform/$token'
    | '/api/admin/ingests/$id/reprocess'
    | '/api/admin/ingests/$id/resolve'
    | '/api/admin/report-ingests/$id/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/no-access'
    | '/platform'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/insights'
    | '/profile'
    | '/users'
    | '/api/apply'
    | '/api/digest-unsubscribe'
    | '/api/rounds'
    | '/api/submit-report'
    | '/applications/$applicationId'
    | '/awards/$awardId'
    | '/finance/balance'
    | '/partnerships/$partnershipId'
    | '/reports/$reportKey'
    | '/settings/activity'
    | '/settings/api-keys'
    | '/settings/award-letter'
    | '/settings/budget'
    | '/settings/data-import'
    | '/settings/giving-strategy'
    | '/settings/submissions'
    | '/settings/team'
    | '/settings/voting'
    | '/shortlist/set-up-awards'
    | '/api/admin/awards'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/deprivation-probe'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/admin/report-canonical-fields'
    | '/api/admin/report-ingests'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/cron/finance-digest'
    | '/api/internal/pipeline'
    | '/api/round/$roundId'
    | '/applications'
    | '/awards'
    | '/finance'
    | '/partnerships'
    | '/programmes'
    | '/reports'
    | '/rounds'
    | '/settings'
    | '/shortlist'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/report-ingests/$id'
    | '/api/webhooks/typeform/$token'
    | '/api/admin/ingests/$id/reprocess'
    | '/api/admin/ingests/$id/resolve'
    | '/api/admin/report-ingests/$id/resolve'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/no-access'
    | '/platform'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/applications'
    | '/_authenticated/awards'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/insights'
    | '/_authenticated/partnerships'
    | '/_authenticated/profile'
    | '/_authenticated/programmes'
    | '/_authenticated/reports'
    | '/_authenticated/rounds'
    | '/_authenticated/settings'
    | '/_authenticated/shortlist'
    | '/_authenticated/users'
    | '/api/apply'
    | '/api/digest-unsubscribe'
    | '/api/rounds'
    | '/api/submit-report'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/awards/$awardId'
    | '/_authenticated/finance/balance'
    | '/_authenticated/partnerships/$partnershipId'
    | '/_authenticated/reports/$reportKey'
    | '/_authenticated/settings/activity'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/award-letter'
    | '/_authenticated/settings/budget'
    | '/_authenticated/settings/data-import'
    | '/_authenticated/settings/giving-strategy'
    | '/_authenticated/settings/submissions'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/voting'
    | '/_authenticated/shortlist/set-up-awards'
    | '/api/admin/awards'
    | '/api/admin/canonical-fields'
    | '/api/admin/clients'
    | '/api/admin/deprivation-probe'
    | '/api/admin/ingests'
    | '/api/admin/mappings'
    | '/api/admin/report-canonical-fields'
    | '/api/admin/report-ingests'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/cron/finance-digest'
    | '/api/internal/pipeline'
    | '/api/round/$roundId'
    | '/_authenticated/applications/'
    | '/_authenticated/awards/'
    | '/_authenticated/finance/'
    | '/_authenticated/partnerships/'
    | '/_authenticated/programmes/'
    | '/_authenticated/reports/'
    | '/_authenticated/rounds/'
    | '/_authenticated/settings/'
    | '/_authenticated/shortlist/'
    | '/api/admin/ingests/$id'
    | '/api/admin/mappings/$id'
    | '/api/admin/report-ingests/$id'
    | '/api/webhooks/typeform/$token'
    | '/api/admin/ingests/$id/reprocess'
    | '/api/admin/ingests/$id/resolve'
    | '/api/admin/report-ingests/$id/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  NoAccessRoute: typeof NoAccessRoute
  PlatformRoute: typeof PlatformRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiDigestUnsubscribeRoute: typeof ApiDigestUnsubscribeRoute
  ApiRoundsRoute: typeof ApiRoundsRoute
  ApiSubmitReportRoute: typeof ApiSubmitReportRoute
  ApiAdminAwardsRoute: typeof ApiAdminAwardsRoute
  ApiAdminCanonicalFieldsRoute: typeof ApiAdminCanonicalFieldsRoute
  ApiAdminClientsRoute: typeof ApiAdminClientsRoute
  ApiAdminDeprivationProbeRoute: typeof ApiAdminDeprivationProbeRoute
  ApiAdminIngestsRoute: typeof ApiAdminIngestsRouteWithChildren
  ApiAdminMappingsRoute: typeof ApiAdminMappingsRouteWithChildren
  ApiAdminReportCanonicalFieldsRoute: typeof ApiAdminReportCanonicalFieldsRoute
  ApiAdminReportIngestsRoute: typeof ApiAdminReportIngestsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarUserIdRoute: typeof ApiAvatarUserIdRoute
  ApiCronFinanceDigestRoute: typeof ApiCronFinanceDigestRoute
  ApiInternalPipelineRoute: typeof ApiInternalPipelineRoute
  ApiRoundRoundIdRoute: typeof ApiRoundRoundIdRoute
  ApiWebhooksTypeformTokenRoute: typeof ApiWebhooksTypeformTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/awards': {
      id: '/_authenticated/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AuthenticatedAwardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partnerships': {
      id: '/_authenticated/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof AuthenticatedPartnershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programmes': {
      id: '/_authenticated/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AuthenticatedProgrammesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rounds': {
      id: '/_authenticated/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof AuthenticatedRoundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shortlist': {
      id: '/_authenticated/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof AuthenticatedShortlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-unsubscribe': {
      id: '/api/digest-unsubscribe'
      path: '/api/digest-unsubscribe'
      fullPath: '/api/digest-unsubscribe'
      preLoaderRoute: typeof ApiDigestUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rounds': {
      id: '/api/rounds'
      path: '/api/rounds'
      fullPath: '/api/rounds'
      preLoaderRoute: typeof ApiRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-report': {
      id: '/api/submit-report'
      path: '/api/submit-report'
      fullPath: '/api/submit-report'
      preLoaderRoute: typeof ApiSubmitReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/awards/': {
      id: '/_authenticated/awards/'
      path: '/'
      fullPath: '/awards/'
      preLoaderRoute: typeof AuthenticatedAwardsIndexRouteImport
      parentRoute: typeof AuthenticatedAwardsRoute
    }
    '/_authenticated/awards/$awardId': {
      id: '/_authenticated/awards/$awardId'
      path: '/$awardId'
      fullPath: '/awards/$awardId'
      preLoaderRoute: typeof AuthenticatedAwardsAwardIdRouteImport
      parentRoute: typeof AuthenticatedAwardsRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/balance': {
      id: '/_authenticated/finance/balance'
      path: '/balance'
      fullPath: '/finance/balance'
      preLoaderRoute: typeof AuthenticatedFinanceBalanceRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/partnerships/': {
      id: '/_authenticated/partnerships/'
      path: '/'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof AuthenticatedPartnershipsIndexRouteImport
      parentRoute: typeof AuthenticatedPartnershipsRoute
    }
    '/_authenticated/partnerships/$partnershipId': {
      id: '/_authenticated/partnerships/$partnershipId'
      path: '/$partnershipId'
      fullPath: '/partnerships/$partnershipId'
      preLoaderRoute: typeof AuthenticatedPartnershipsPartnershipIdRouteImport
      parentRoute: typeof AuthenticatedPartnershipsRoute
    }
    '/_authenticated/programmes/': {
      id: '/_authenticated/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof AuthenticatedProgrammesIndexRouteImport
      parentRoute: typeof AuthenticatedProgrammesRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/$reportKey': {
      id: '/_authenticated/reports/$reportKey'
      path: '/$reportKey'
      fullPath: '/reports/$reportKey'
      preLoaderRoute: typeof AuthenticatedReportsReportKeyRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/rounds/': {
      id: '/_authenticated/rounds/'
      path: '/'
      fullPath: '/rounds/'
      preLoaderRoute: typeof AuthenticatedRoundsIndexRouteImport
      parentRoute: typeof AuthenticatedRoundsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/award-letter': {
      id: '/_authenticated/settings/award-letter'
      path: '/award-letter'
      fullPath: '/settings/award-letter'
      preLoaderRoute: typeof AuthenticatedSettingsAwardLetterRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/budget': {
      id: '/_authenticated/settings/budget'
      path: '/budget'
      fullPath: '/settings/budget'
      preLoaderRoute: typeof AuthenticatedSettingsBudgetRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/data-import': {
      id: '/_authenticated/settings/data-import'
      path: '/data-import'
      fullPath: '/settings/data-import'
      preLoaderRoute: typeof AuthenticatedSettingsDataImportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/giving-strategy': {
      id: '/_authenticated/settings/giving-strategy'
      path: '/giving-strategy'
      fullPath: '/settings/giving-strategy'
      preLoaderRoute: typeof AuthenticatedSettingsGivingStrategyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/submissions': {
      id: '/_authenticated/settings/submissions'
      path: '/submissions'
      fullPath: '/settings/submissions'
      preLoaderRoute: typeof AuthenticatedSettingsSubmissionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/voting': {
      id: '/_authenticated/settings/voting'
      path: '/voting'
      fullPath: '/settings/voting'
      preLoaderRoute: typeof AuthenticatedSettingsVotingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/shortlist/': {
      id: '/_authenticated/shortlist/'
      path: '/'
      fullPath: '/shortlist/'
      preLoaderRoute: typeof AuthenticatedShortlistIndexRouteImport
      parentRoute: typeof AuthenticatedShortlistRoute
    }
    '/_authenticated/shortlist/set-up-awards': {
      id: '/_authenticated/shortlist/set-up-awards'
      path: '/set-up-awards'
      fullPath: '/shortlist/set-up-awards'
      preLoaderRoute: typeof AuthenticatedShortlistSetUpAwardsRouteImport
      parentRoute: typeof AuthenticatedShortlistRoute
    }
    '/api/admin/awards': {
      id: '/api/admin/awards'
      path: '/api/admin/awards'
      fullPath: '/api/admin/awards'
      preLoaderRoute: typeof ApiAdminAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/canonical-fields': {
      id: '/api/admin/canonical-fields'
      path: '/api/admin/canonical-fields'
      fullPath: '/api/admin/canonical-fields'
      preLoaderRoute: typeof ApiAdminCanonicalFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clients': {
      id: '/api/admin/clients'
      path: '/api/admin/clients'
      fullPath: '/api/admin/clients'
      preLoaderRoute: typeof ApiAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deprivation-probe': {
      id: '/api/admin/deprivation-probe'
      path: '/api/admin/deprivation-probe'
      fullPath: '/api/admin/deprivation-probe'
      preLoaderRoute: typeof ApiAdminDeprivationProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingests': {
      id: '/api/admin/ingests'
      path: '/api/admin/ingests'
      fullPath: '/api/admin/ingests'
      preLoaderRoute: typeof ApiAdminIngestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mappings': {
      id: '/api/admin/mappings'
      path: '/api/admin/mappings'
      fullPath: '/api/admin/mappings'
      preLoaderRoute: typeof ApiAdminMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report-canonical-fields': {
      id: '/api/admin/report-canonical-fields'
      path: '/api/admin/report-canonical-fields'
      fullPath: '/api/admin/report-canonical-fields'
      preLoaderRoute: typeof ApiAdminReportCanonicalFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report-ingests': {
      id: '/api/admin/report-ingests'
      path: '/api/admin/report-ingests'
      fullPath: '/api/admin/report-ingests'
      preLoaderRoute: typeof ApiAdminReportIngestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$userId': {
      id: '/api/avatar/$userId'
      path: '/api/avatar/$userId'
      fullPath: '/api/avatar/$userId'
      preLoaderRoute: typeof ApiAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/finance-digest': {
      id: '/api/cron/finance-digest'
      path: '/api/cron/finance-digest'
      fullPath: '/api/cron/finance-digest'
      preLoaderRoute: typeof ApiCronFinanceDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/pipeline': {
      id: '/api/internal/pipeline'
      path: '/api/internal/pipeline'
      fullPath: '/api/internal/pipeline'
      preLoaderRoute: typeof ApiInternalPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/round/$roundId': {
      id: '/api/round/$roundId'
      path: '/api/round/$roundId'
      fullPath: '/api/round/$roundId'
      preLoaderRoute: typeof ApiRoundRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingests/$id': {
      id: '/api/admin/ingests/$id'
      path: '/$id'
      fullPath: '/api/admin/ingests/$id'
      preLoaderRoute: typeof ApiAdminIngestsIdRouteImport
      parentRoute: typeof ApiAdminIngestsRoute
    }
    '/api/admin/mappings/$id': {
      id: '/api/admin/mappings/$id'
      path: '/$id'
      fullPath: '/api/admin/mappings/$id'
      preLoaderRoute: typeof ApiAdminMappingsIdRouteImport
      parentRoute: typeof ApiAdminMappingsRoute
    }
    '/api/admin/report-ingests/$id': {
      id: '/api/admin/report-ingests/$id'
      path: '/$id'
      fullPath: '/api/admin/report-ingests/$id'
      preLoaderRoute: typeof ApiAdminReportIngestsIdRouteImport
      parentRoute: typeof ApiAdminReportIngestsRoute
    }
    '/api/webhooks/typeform/$token': {
      id: '/api/webhooks/typeform/$token'
      path: '/api/webhooks/typeform/$token'
      fullPath: '/api/webhooks/typeform/$token'
      preLoaderRoute: typeof ApiWebhooksTypeformTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingests/$id/reprocess': {
      id: '/api/admin/ingests/$id/reprocess'
      path: '/reprocess'
      fullPath: '/api/admin/ingests/$id/reprocess'
      preLoaderRoute: typeof ApiAdminIngestsIdReprocessRouteImport
      parentRoute: typeof ApiAdminIngestsIdRoute
    }
    '/api/admin/ingests/$id/resolve': {
      id: '/api/admin/ingests/$id/resolve'
      path: '/resolve'
      fullPath: '/api/admin/ingests/$id/resolve'
      preLoaderRoute: typeof ApiAdminIngestsIdResolveRouteImport
      parentRoute: typeof ApiAdminIngestsIdRoute
    }
    '/api/admin/report-ingests/$id/resolve': {
      id: '/api/admin/report-ingests/$id/resolve'
      path: '/resolve'
      fullPath: '/api/admin/report-ingests/$id/resolve'
      preLoaderRoute: typeof ApiAdminReportIngestsIdResolveRouteImport
      parentRoute: typeof ApiAdminReportIngestsIdRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedAwardsRouteChildren {
  AuthenticatedAwardsAwardIdRoute: typeof AuthenticatedAwardsAwardIdRoute
  AuthenticatedAwardsIndexRoute: typeof AuthenticatedAwardsIndexRoute
}

const AuthenticatedAwardsRouteChildren: AuthenticatedAwardsRouteChildren = {
  AuthenticatedAwardsAwardIdRoute: AuthenticatedAwardsAwardIdRoute,
  AuthenticatedAwardsIndexRoute: AuthenticatedAwardsIndexRoute,
}

const AuthenticatedAwardsRouteWithChildren =
  AuthenticatedAwardsRoute._addFileChildren(AuthenticatedAwardsRouteChildren)

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceBalanceRoute: typeof AuthenticatedFinanceBalanceRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceBalanceRoute: AuthenticatedFinanceBalanceRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedPartnershipsRouteChildren {
  AuthenticatedPartnershipsPartnershipIdRoute: typeof AuthenticatedPartnershipsPartnershipIdRoute
  AuthenticatedPartnershipsIndexRoute: typeof AuthenticatedPartnershipsIndexRoute
}

const AuthenticatedPartnershipsRouteChildren: AuthenticatedPartnershipsRouteChildren =
  {
    AuthenticatedPartnershipsPartnershipIdRoute:
      AuthenticatedPartnershipsPartnershipIdRoute,
    AuthenticatedPartnershipsIndexRoute: AuthenticatedPartnershipsIndexRoute,
  }

const AuthenticatedPartnershipsRouteWithChildren =
  AuthenticatedPartnershipsRoute._addFileChildren(
    AuthenticatedPartnershipsRouteChildren,
  )

interface AuthenticatedProgrammesRouteChildren {
  AuthenticatedProgrammesIndexRoute: typeof AuthenticatedProgrammesIndexRoute
}

const AuthenticatedProgrammesRouteChildren: AuthenticatedProgrammesRouteChildren =
  {
    AuthenticatedProgrammesIndexRoute: AuthenticatedProgrammesIndexRoute,
  }

const AuthenticatedProgrammesRouteWithChildren =
  AuthenticatedProgrammesRoute._addFileChildren(
    AuthenticatedProgrammesRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportKeyRoute: typeof AuthenticatedReportsReportKeyRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportKeyRoute: AuthenticatedReportsReportKeyRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRoundsRouteChildren {
  AuthenticatedRoundsIndexRoute: typeof AuthenticatedRoundsIndexRoute
}

const AuthenticatedRoundsRouteChildren: AuthenticatedRoundsRouteChildren = {
  AuthenticatedRoundsIndexRoute: AuthenticatedRoundsIndexRoute,
}

const AuthenticatedRoundsRouteWithChildren =
  AuthenticatedRoundsRoute._addFileChildren(AuthenticatedRoundsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAwardLetterRoute: typeof AuthenticatedSettingsAwardLetterRoute
  AuthenticatedSettingsBudgetRoute: typeof AuthenticatedSettingsBudgetRoute
  AuthenticatedSettingsDataImportRoute: typeof AuthenticatedSettingsDataImportRoute
  AuthenticatedSettingsGivingStrategyRoute: typeof AuthenticatedSettingsGivingStrategyRoute
  AuthenticatedSettingsSubmissionsRoute: typeof AuthenticatedSettingsSubmissionsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsVotingRoute: typeof AuthenticatedSettingsVotingRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAwardLetterRoute: AuthenticatedSettingsAwardLetterRoute,
  AuthenticatedSettingsBudgetRoute: AuthenticatedSettingsBudgetRoute,
  AuthenticatedSettingsDataImportRoute: AuthenticatedSettingsDataImportRoute,
  AuthenticatedSettingsGivingStrategyRoute:
    AuthenticatedSettingsGivingStrategyRoute,
  AuthenticatedSettingsSubmissionsRoute: AuthenticatedSettingsSubmissionsRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsVotingRoute: AuthenticatedSettingsVotingRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedShortlistRouteChildren {
  AuthenticatedShortlistSetUpAwardsRoute: typeof AuthenticatedShortlistSetUpAwardsRoute
  AuthenticatedShortlistIndexRoute: typeof AuthenticatedShortlistIndexRoute
}

const AuthenticatedShortlistRouteChildren: AuthenticatedShortlistRouteChildren =
  {
    AuthenticatedShortlistSetUpAwardsRoute:
      AuthenticatedShortlistSetUpAwardsRoute,
    AuthenticatedShortlistIndexRoute: AuthenticatedShortlistIndexRoute,
  }

const AuthenticatedShortlistRouteWithChildren =
  AuthenticatedShortlistRoute._addFileChildren(
    AuthenticatedShortlistRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedAwardsRoute: typeof AuthenticatedAwardsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedPartnershipsRoute: typeof AuthenticatedPartnershipsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgrammesRoute: typeof AuthenticatedProgrammesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRoundsRoute: typeof AuthenticatedRoundsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedShortlistRoute: typeof AuthenticatedShortlistRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedAwardsRoute: AuthenticatedAwardsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedPartnershipsRoute: AuthenticatedPartnershipsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgrammesRoute: AuthenticatedProgrammesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRoundsRoute: AuthenticatedRoundsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedShortlistRoute: AuthenticatedShortlistRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAdminIngestsIdRouteChildren {
  ApiAdminIngestsIdReprocessRoute: typeof ApiAdminIngestsIdReprocessRoute
  ApiAdminIngestsIdResolveRoute: typeof ApiAdminIngestsIdResolveRoute
}

const ApiAdminIngestsIdRouteChildren: ApiAdminIngestsIdRouteChildren = {
  ApiAdminIngestsIdReprocessRoute: ApiAdminIngestsIdReprocessRoute,
  ApiAdminIngestsIdResolveRoute: ApiAdminIngestsIdResolveRoute,
}

const ApiAdminIngestsIdRouteWithChildren =
  ApiAdminIngestsIdRoute._addFileChildren(ApiAdminIngestsIdRouteChildren)

interface ApiAdminIngestsRouteChildren {
  ApiAdminIngestsIdRoute: typeof ApiAdminIngestsIdRouteWithChildren
}

const ApiAdminIngestsRouteChildren: ApiAdminIngestsRouteChildren = {
  ApiAdminIngestsIdRoute: ApiAdminIngestsIdRouteWithChildren,
}

const ApiAdminIngestsRouteWithChildren = ApiAdminIngestsRoute._addFileChildren(
  ApiAdminIngestsRouteChildren,
)

interface ApiAdminMappingsRouteChildren {
  ApiAdminMappingsIdRoute: typeof ApiAdminMappingsIdRoute
}

const ApiAdminMappingsRouteChildren: ApiAdminMappingsRouteChildren = {
  ApiAdminMappingsIdRoute: ApiAdminMappingsIdRoute,
}

const ApiAdminMappingsRouteWithChildren =
  ApiAdminMappingsRoute._addFileChildren(ApiAdminMappingsRouteChildren)

interface ApiAdminReportIngestsIdRouteChildren {
  ApiAdminReportIngestsIdResolveRoute: typeof ApiAdminReportIngestsIdResolveRoute
}

const ApiAdminReportIngestsIdRouteChildren: ApiAdminReportIngestsIdRouteChildren =
  {
    ApiAdminReportIngestsIdResolveRoute: ApiAdminReportIngestsIdResolveRoute,
  }

const ApiAdminReportIngestsIdRouteWithChildren =
  ApiAdminReportIngestsIdRoute._addFileChildren(
    ApiAdminReportIngestsIdRouteChildren,
  )

interface ApiAdminReportIngestsRouteChildren {
  ApiAdminReportIngestsIdRoute: typeof ApiAdminReportIngestsIdRouteWithChildren
}

const ApiAdminReportIngestsRouteChildren: ApiAdminReportIngestsRouteChildren = {
  ApiAdminReportIngestsIdRoute: ApiAdminReportIngestsIdRouteWithChildren,
}

const ApiAdminReportIngestsRouteWithChildren =
  ApiAdminReportIngestsRoute._addFileChildren(
    ApiAdminReportIngestsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  NoAccessRoute: NoAccessRoute,
  PlatformRoute: PlatformRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiDigestUnsubscribeRoute: ApiDigestUnsubscribeRoute,
  ApiRoundsRoute: ApiRoundsRoute,
  ApiSubmitReportRoute: ApiSubmitReportRoute,
  ApiAdminAwardsRoute: ApiAdminAwardsRoute,
  ApiAdminCanonicalFieldsRoute: ApiAdminCanonicalFieldsRoute,
  ApiAdminClientsRoute: ApiAdminClientsRoute,
  ApiAdminDeprivationProbeRoute: ApiAdminDeprivationProbeRoute,
  ApiAdminIngestsRoute: ApiAdminIngestsRouteWithChildren,
  ApiAdminMappingsRoute: ApiAdminMappingsRouteWithChildren,
  ApiAdminReportCanonicalFieldsRoute: ApiAdminReportCanonicalFieldsRoute,
  ApiAdminReportIngestsRoute: ApiAdminReportIngestsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarUserIdRoute: ApiAvatarUserIdRoute,
  ApiCronFinanceDigestRoute: ApiCronFinanceDigestRoute,
  ApiInternalPipelineRoute: ApiInternalPipelineRoute,
  ApiRoundRoundIdRoute: ApiRoundRoundIdRoute,
  ApiWebhooksTypeformTokenRoute: ApiWebhooksTypeformTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
